services:
  app:
    image: termitx/test
    #ports:
    #  - "80:8000"
    network_mode: "service:ibeam"
    depends_on:
      - ibeam
  ibeam:
    image: voyz/ibeam
    ports:
      - "5000:5000"
      - "80:8000"
    #restart: always
    environment:
      IBEAM_ACCOUNT: gazde0001 
      IBEAM_PASSWORD: mala1jabukapaper

